### PR TITLE
Update the package.json 

### PR DESCRIPTION
**Pull request by rbecheras**
Now users find your repo mooz ;)

Plus, an entry for "main" is recommended, and the package version is up to 1.0.0.

### CODE REVIEW

**Comment by mooz** [comment]
Great. Thx!

**Comment by rbecheras** [comment]
Could you tag the version ?

    git checkout master
    git pull origin
    git tag v1.0.0
    git push --tags origin

**Comment by mooz** [comment]
Tagged. Thx!

**Comment by alexiskattan** [comment]
I'm getting an error now :(

(function (exports, require, module, __filename, __dirname) { %PDF-1.3
                                                              ^
SyntaxError: Unexpected token %
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)

**Comment by rbecheras** [comment]
I think it's not about theses commits that didn't touch the code..

What is the file 'module.js' ?
Indeed, this stack trace show '%PDF-1.3' as start of this function that is not a regular syntax at all, but it isn't a part of node-pdf-image package at all so ...

**Comment by mooz** [comment]
@alexiskattan Could you open a separate issue and provide test code that can produce the error?

**Pull request merged**
